import './globals.css'
// import './scrollbar.css';

// import { Inter } from 'next/font/google'
import Header from '@/components/layout/Header'
import Wrapper from '@/components/shared/wrapper'
import Footer from '@/views/Fotter';
import ReduxProvider from '@/utils/ReduxProvider';
import toast, { Toaster } from 'react-hot-toast';
import { ClerkProvider, auth } from '@clerk/nextjs'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const { userId }: any = auth();
  return (
    <ClerkProvider>
      <ReduxProvider>
        <html lang="en">
          <body>
            <Wrapper>
              <Header userId={userId} />
              <main className='px-8'>
                {children}
                <Toaster />
              </main>
              <Footer />
            </Wrapper>
          </body>
        </html>
      </ReduxProvider>
    </ClerkProvider>

  )
}
